# Generated by Django 4.2.1 on 2023-06-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='addresses',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_valid',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
